version: "3"
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - kea
  kea:
    build:
      context: .
      dockerfile: kea.Dockerfile
    expose:
    - "8080"
  tests:
    build:
      context: .
      dockerfile: terraform.Dockerfile
    depends_on:
    - api
    - kea
