name: CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Create Terraform plugins directory
      run: mkdir -p ~/.terraform.d/plugins/linux_amd64

    - name: Build
      env: 
        CGO_ENABLED: "0"
        GOOS: linux
        GOARCH: amd64
      run: go build -v -a -o ~/.terraform.d/plugins/linux_amd64/terraform-provider-kea-dhcp4_v1.0_x4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.20

    - name: Set up test environment
      run: docker network create kea
      
    - run: docker build -t kea-test -f kea.Dockerfile .
    - run: docker build -t nginx-test -f api.Dockerfile .
    - run: docker run -d --network kea --name kea kea-test
    - run: docker run -d --network kea --name api -p 127.0.0.1:8080:8080/tcp nginx-test

    - name: Terraform init
      working-directory: test-data/terraform
      run: terraform init

    - name: Terraform apply
      working-directory: test-data/terraform
      run: terraform apply -auto-approve

    - name: Terraform destroy
      working-directory: test-data/terraform
      run: terraform apply -auto-approve